### PR TITLE
task solution

### PR DESCRIPTION
**Pull request by Kurman-Off**
Link - https://kurman-off.github.io/js_task_fix_form_DOM/

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Screenshot 2024-07-22 at 17 31 08
Great work! Consider adding spaces between words

**Review by lerastarynets — CHANGES_REQUESTED** [review]
Good job in fixing prev comments! 
Pls try to pass all tests, if your tests pass locally, but you encounter a problem in server tests, pls attach a screen of all local tests passing

**Comment by Kurman-Off** [comment]
Link - https://kurman-off.github.io/js_task_fix_form_DOM/
image

**Comment by Kurman-Off** [comment]
image_2024-07-22_20-19-47

**Comment by Kurman-Off** [comment]
у мене все добре

**Comment by Kurman-Off** [comment]
все працює а тести не проходять ніяк

**Pull request closed without merging**
